version: '3.6'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: proxy_container
    depends_on:
      - backend_service
  frontend_service:
    image: frontend-service
    build:
      context: ./frontend-example-docker/
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost/api/
    container_name: frontend_container
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sekret
      - POSTGRES_USER=docker
      - POSTGRES_DB=postgres_db
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: db_postgres
  backend_service:
    image: backend-image
    build:
      context: ./backend-example-docker/
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost/
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=docker
      - DB_PASSWORD=sekret
      - DB_NAME=postgres_db
      - DB_HOST=db_postgres
    container_name: backend_container
    depends_on: 
      - db
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    container_name: redis
